spring.application.name=MiPriApi

spring.datasource.url=jdbc:mysql://localhost:3306/BuenSabor?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


codigo.mercadoPago= "token.mp"

# puerto de ejecucion
server.port=8080


# CONFIGURACION CLOUDINARY
cloudinary.cloud_name=dileh0rti
cloudinary.api_key=373953261952439
cloudinary.api_secret=7V5FgbGSs2mB-9-aOq-2y9f-1k4

# CONFIGURACION DE SEGURIDAD
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
auth0.audience=${AUTH0_AUDIENCE}
web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
auth0.domain=${AUTH0_DOMAIN}
auth0.clientId=${AUTH0_CLIENT_ID}
auth0.clientSecret=${AUTH0_CLIENT_SECRET}

# MERCADO PAGO
mercado-pago.access-token=APP_USR-4369973637072207-110611-ba5025f38a2779043a4cee0f94f2c0c4-2079159129





logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

#definimos tamaño para subir archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB