spring.application.name=MiPriApi

spring.datasource.url=jdbc:mysql://localhost:3306/BuenSabor?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


codigo.mercadoPago= "token.mp"

# puerto de ejecucion
server.port=8080
